### ISSUE TITLE
i still cannot understand why i should have this mod, can u explain the detail of the situation that this mod improved

### ISSUE THREAD

**Issue by CoolLKKPS** [ButteryStancakes/MeleeFixes#1]
same as topic

**Comment by ButteryStancakes** [comment]
Did you read the [Thunderstore description](https://thunderstore.io/c/lethal-company/p/ButteryStancakes/MeleeFixes/)? I feel like it does a pretty good job explaining the bugs that I fixed

**Comment by CoolLKKPS** [comment]
hmm, i didn't reproduce the issue so i confused at that moment, but anyway i installed this mod now
